### ISSUE TITLE
How to install in Eclipse

### ISSUE THREAD

**Issue by RajeshShah** [justinkb/DashLookup#1]
Hi,

Thanks for the plugin. I am however having difficulties in installing it. I did the first 2 steps i.e., Downloaded and added the unzipped project to the Workspace. But when I export, I do not get any options for Deployable Plugin.

Can you help me out this?

Thanks,
Rajesh Shah

**Comment by yimingpeng** [comment]
It is called "Deployable plug-ins and fragments" inside Plug-in Development category. See below
![screen shot 2013-11-28 at 1 39 36 pm](https://f.cloud.github.com/assets/5914252/1636217/d3a5a2dc-57c5-11e3-992c-d6897fdb450d.png)

**Comment by RajeshShah** [comment]
Thanks. Unfortunately, I do not see the Plug-in Development option in my eclipse when Exporting. Will have to figure  that out.

**Comment by yimingpeng** [comment]
Did you download the right version of eclipse? I am using eclipse classic, it has this option.

**Comment by RajeshShah** [comment]
My eclipse version:
![image](https://f.cloud.github.com/assets/3532422/1638274/921ba7fc-5807-11e3-8eb5-a8b8518b70b1.png)

**Comment by yimingpeng** [comment]
You could install plug-in development environment from "install new software".
![screen shot 2013-11-29 at 11 27 41 am](https://f.cloud.github.com/assets/5914252/1642336/7b1abb68-587c-11e3-8cd5-83ffedf346ff.png)

**Comment by RajeshShah** [comment]
Thanks. It worked. BTW it currently only searches in Dash, does it also copy the snippet from Dash with some command or do I have to use the standard Use feature of Dash?
